# Generated by Django 2.2.5 on 2019-10-17 11:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('number', models.CharField(max_length=3, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Frame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True, unique=True)),
                ('model_name', models.CharField(max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('max_depth', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='IdentifierType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('max_depth', models.IntegerField(blank=True, null=True)),
                ('public', models.BooleanField(default=True)),
                ('last_modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_indicators', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='IndicatorParameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_min', models.CharField(max_length=100, null=True)),
                ('year_max', models.CharField(max_length=100, null=True)),
                ('readable_equation', models.TextField(null=True)),
                ('displaying', models.CharField(max_length=100, null=True)),
                ('institution_type_number', models.IntegerField(null=True)),
                ('institution_type_string', models.CharField(max_length=4, null=True)),
                ('type_budget', models.CharField(max_length=100, null=True)),
                ('original_equation', models.TextField(null=True)),
                ('depth', models.IntegerField(null=True)),
                ('indicator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='open_anafi.Indicator')),
            ],
        ),
        migrations.CreateModel(
            name='InstitutionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('number', models.IntegerField()),
                ('legal_status', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Nomenclature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TranslationTableEstablishmentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_budget', models.CharField(max_length=100, null=True)),
                ('letter', models.CharField(max_length=1, null=True)),
                ('type_establishment', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Variable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('numero_compte', models.CharField(max_length=100, null=True)),
                ('type_solde', models.CharField(max_length=100, null=True)),
                ('solde', models.CharField(max_length=100, null=True)),
                ('indicator_parameter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_indicator', to='open_anafi.IndicatorParameter')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_min', models.CharField(max_length=100, null=True)),
                ('year_max', models.CharField(max_length=100, null=True)),
                ('identifier', models.TextField(null=True)),
                ('identifier_type', models.CharField(max_length=100, null=True)),
                ('state', models.CharField(max_length=100, null=True)),
                ('name', models.CharField(max_length=400, null=True)),
                ('date', models.DateField(auto_now=True)),
                ('frame', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='open_anafi.Frame')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='IndicatorLibelle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=100, null=True, unique=True)),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='libelles', to='open_anafi.Indicator')),
            ],
        ),
        migrations.AddField(
            model_name='frame',
            name='identifiers_type',
            field=models.ManyToManyField(blank=True, related_name='frames', to='open_anafi.IdentifierType'),
        ),
        migrations.AddField(
            model_name='frame',
            name='indicators',
            field=models.ManyToManyField(blank=True, related_name='frames', to='open_anafi.Indicator'),
        ),
        migrations.AddField(
            model_name='frame',
            name='institutions_type',
            field=models.ManyToManyField(blank=True, related_name='frames', to='open_anafi.InstitutionType'),
        ),
        migrations.AddField(
            model_name='frame',
            name='nomenclature',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='frames', to='open_anafi.Nomenclature'),
        ),
    ]
