# Generated by Django 2.2.5 on 2020-01-06 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('open_anafi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='frame_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='indicatorlibelle',
            name='libelle',
            field=models.TextField(null=True),
        ),
    ]
